### ISSUE TITLE
Avatar Color Issue

### ISSUE THREAD

**Issue by torgeadelin** [momentum-design/tokens#30]
The light colour of the token below is wrong, it should be white.

```css
/* taken from dist/lightWebex.css */
.md-theme-lightWebex {
  ...
  --avatar-color-avatar-text: rgba(0, 0, 0, 0.95);
  ...
}
```
